mutation UpdateClientByPk(
  $id: String!,
  $redirectURI: String,
) {
  client: update_clients_by_pk(
    pk_columns: {id: $id},
    _set: {redirect_uri: $redirectURI}
  ) {
    id
    redirect_uri
  }
}
